# version: "3.8"
services:
  whisper:
    build: ./whisper/
    depends_on:
      - rabbitmq

  # app:
  #   build: ./app/
  #   image: event-planner-api:latest 
  #   env_file:
  #   - ./app/.env
  #   volumes:
  #     - ./app:/app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #     - rabbitmq
  #     - bertanswer1
  #     - bertanswer2

  # web:
  #   build: ./web/
  #   ports:
  #    - "5173:5173"
  #   depends_on:
  #    - app

  db:
    image: postgres:16-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    #
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=speechinsight
    ports: 
     - "5432:5432"

  app:
    build: ./app/
    image: event-planner-api:latest 
    env_file:
    - ./app/.env
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
     
  # web:
  #   image: python:3.11-alpine
  #   command: sh  -c "cd speechinsight && pip install -r requirements.txt && cd app && ls && uvicorn app\main:app --host 0.0.0.0 --port 8000"
  #   volumes:
  #     - .:/speechinsight
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_HOST=${DB_HOST}
  #     - DB_PORT=${DB_PORT}
  #     - DB_USER=${DB_USER}
  #     - DB_PASS=${DB_PASS}
  #     - DB_NAME=${DB_NAME}

  rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${POSTGRES_USER}

