version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../config/.env
    volumes:
      - ../:/app
    depends_on:
      - database
      - rabbitmq

  web-proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  db_data:
